//=================================================
// DO NOT EDIT THIS FILE
//
// This file is part of the standard chat service
// for NV:MP. You may be encouraged to edit this
// file, but for your safety please DO NOT change
// the contents.
// 
// If you would like to change the style of the
// chat, create your own .css files and add them
// to the chat.html document using the proper 
// <link> tags.
//=================================================
function ChatManager()
{
    const kViewableMessageLimit = 30;        // How many messages should be visible by the player at a time.
    const kDefaultColour = [255, 255, 255];  // The default colour to resort to invalid colour formats.
    const kDimTimeRemote = 10000;            // Time before the panel dims from a remote message.
    const kDimTimeLocal = 2000;              // Time before the panel dims from coming out of the input box.

    const kMaxMessageHistory = 80;

    const kKeyboardInput =
    {
        escape : 27,
        enter  : 13,
        up     : 38,
        down   : 40,
        pageup   : 33,
        pagedown : 34
    };

    var message_history = [];
    var history_index = 0;
    var gamemode = null;

    // DOM element cache.
    var input_box, messages, content = null;

    // Temporary storage.
    var temp_placeholder = null;

    // Timers
    var dim_timer = null,
        gm_timer = null;

  
    this.record_message = function (message) {
        if (message_history.length >= kMaxMessageHistory) {
            message_history.pop();
        }

        // Reset index back to start of list.
        history_index = 0;
        message_history.unshift(message)
    };

    this.get_last_message = function (index) {
        if (index >= message_history.length) {
            return null;
        }

        return message_history[index];
    };

    this.check_for_gm = function () {
        var faction_status = app.sio_get("NetServerConfig", "sv_enablefactions");
        if (faction_status !== null && faction_status == 1)
        {
            gamemode = new Factions(this);
            clearInterval(gm_timer);
        }
    };

    // Focuses the chat box.
    this.focus = function () {
        $(input_box).focus();
        this.on_input_box_focus();
    };

    this.dim_then_time = function () {
        this.do_dim();
        this.start_undim(kDimTimeRemote);
    };

    this.start_undim = function (t) {
        t = t || kDimTimeLocal;
        this.stop_undim();
        this.dim_timer = setTimeout(this.do_undim.bind(this), t);
    };

    this.stop_undim = function () {
        if (this.dim_timer != null) {
            clearTimeout(this.dim_timer);
            this.dim_timer = null;
        }
    };

    this.do_dim = function () {
        this.stop_undim();
        messages.attr("class", "dim");
        messages.css("overflow-y", "scroll");
    };

    this.do_undim = function () {
        messages.attr("class", "clear");
        messages.css("overflow-y", "hidden");
    };

    this.on_input_box_focus = function () {
        // Go to the bottom of the chat.
        this.reorder();

        // Store the original placeholder and replace it with an empty
        // body to signal that it's waiting for input.
        this.temp_placeholder = input_box.getAttribute("placeholder");

        input_box.setAttribute("placeholder", "");
        input_box.setAttribute("class", "focused");
        this.do_dim();
    };

    this.on_input_box_unfocus = function () {

        // Restore the old placeholder if it was previously saved.
        if (temp_placeholder !== null) {
            input_box.setAttribute("placeholder", temp_placeholder);
            temp_placeholder = null;
        }

        // Clear the text.
        input_box.value = "";
        this.start_undim();
        input_box.setAttribute("class", "");

        window.app.on_losefocus();
    };

    this.blur = function () {

        if (input_box.value.length === 0) {
            $(input_box).blur();
        }

    };

    this.send = function () {
        var text = input_box.value.trim();

        if (text == "") {
            return;
        }

        this.record_message(text);

        switch (text)
        {
            case "/suicide":
            case "/die":
            case "/respawn":
                window.app.fire_suicide();
                return;

            case "/quit":
            case "/q":
                window.app.fire_quit();
                return;
        }

        window.app.on_message(input_box.value);

        input_box.value = "";
        $(input_box).blur();
    };

    this.on_input_box_keypress = function (evt) {
        switch (evt.keyCode)
        {
            //case kKeyboardInput.escape:
            //{
            //    $(input_box).trigger('blur');
            //    break;
            //}
            case kKeyboardInput.enter:
            {
                this.send();
                break;
            }
            case kKeyboardInput.up:
            {
                var msg = this.get_last_message(history_index);
                if (msg) {
                    $(input_box).val(msg);
                    history_index++;
                }
                break;
            }
            case kKeyboardInput.down:
            {
                if (history_index <= 0) {
                    $(input_box).val("");
                    return;
                }
                history_index--;

                var msg = this.get_last_message(history_index);
                if (msg) {
                    $(input_box).val(msg);
                }
                break;
            }
            case kKeyboardInput.pagedown:
            {
                messages.get(0).scrollTop += 100;
                break;
            }
            case kKeyboardInput.pageup:
            {
                messages.get(0).scrollTop -= Math.min(100, messages.get(0).scrollTop);
                break;
            }
        }
    };

    this.reorder = function () {
        var dead_children = messages[0].children.length - kViewableMessageLimit;

        if (dead_children > 0) {
            for (var i = 0; i < dead_children; i++) {
                messages.find("div:first").remove();
            }
        }

        setTimeout(function () {
            var height = messages[0].scrollHeight;
            messages.scrollTop(height);

            this.dim_then_time();
        }.bind(this), 5);
    };

    this._new_message = function (classType, hasNameTag) {
        var result = { _container: null, content: null, nametag: null };

        var container = document.createElement("div");
        container.setAttribute("class", "mitem " + classType);

        result._container = container;

        if (hasNameTag) {
            var nametag = document.createElement("span");
            nametag.setAttribute("class", "nametag");

            container.appendChild(nametag);
            result.nametag = nametag;
        }

        var message = document.createElement("span");
        container.appendChild(message);

        result.content = message;

        messages.append(container);
        this.reorder();

        return result;
    };

    this.parse_colours = function (text) {

        if (text == null) {
            return kDefaultColour;
        }

        var colours = text.split(',');
        if (colours.length != 3) {
            return kDefaultColour;
        }

        for (var i = 0; i < 3; ++i) {
            colours[i] = Number(colours[i]);
        }

        return "rgba(" + colours[0] + "," + colours[1] + "," + colours[2] + ", 255)";
    };

    //---------------------------------------
    // C++ End point API
    //---------------------------------------
    this.addRawMessage = function (text, colour) {

        if (app.sio_get("Chat", "ShowSystemMessages") == 0) {
            return;
        }

        var colours = this.parse_colours(colour);
        var MessageTag = this._new_message("raw", false);

        MessageTag.content.innerText = text;
        MessageTag.content.style.color = colours;
    };

    this.addSystemMessage = function (text, colour) {
        if (app.sio_get("Chat", "ShowSystemMessages") == 0) {
            return;
        }

        var MessageClassName = null;
        var MessageColour = null;
        var colours = this.parse_colours(colour);

        if (text.indexOf("---") === 0)
        {
            MessageClassName = "system_sub_head";
            text = text.substr(3);
        }
        else if (text.indexOf("--") === 0)
        {
            MessageClassName = "system_head";
            text = text.substr(2);
        } else if (text.indexOf("~") === 0)
        {
            MessageClassName = "system_console";
            MessageColour = colours;
            text = text.substr(1);
        }
        else
        {
            MessageClassName = "system";
            MessageColour = colours;
        }

        var MessageTag = this._new_message(MessageClassName);

        if (MessageColour)
        {
            MessageTag.content.style.color = MessageColour;
        }

        MessageTag.content.innerText = text;
    };

    this.addUserMessage = function (channel, name, text, colour) {

        if (app.sio_get("Chat", "ShowPlayerMessages") == 0) {
            return;
        }

        var colours = this.parse_colours(colour);
        var MessageTag = this._new_message("player", true);
        MessageTag.content.innerText = text;

        var tag = null;
        if (channel == "global")
        {
            tag = document.createElement("div");
            tag.setAttribute("class", "nameprefix globaltag");
        }
        else if (channel == "factions")
        {
            tag = document.createElement("div");
            tag.setAttribute("class", "nameprefix factiontag");
        }

        if (tag !== null)
        {
            $(MessageTag.nametag).append(tag);
        }
        
        $(MessageTag.nametag).append( name );
        MessageTag.nametag.style.color = colours;
    };

    this.addWhisperMessage = function (name, text, is_local) {

        if (app.sio_get("Chat", "ShowWhisperMessages") == 0) {
            return;
        }

        // Local messages need a different suffix.
        var MessageTag = this._new_message(is_local ? "whisper-local" : "whisper", true);

        // Setup accordingly.
        MessageTag.content.innerText = text;
        MessageTag.nametag.innerText = name;
    };

    //---------------------------------------
    // Event handlers
    //---------------------------------------
    this.load = function () {
        // Get DOM elements before continuing with messaging initialisation.
        input_box = document.getElementById("message");
        messages = $(document.getElementById("messages"));
        content = $(document.getElementById("content"));
        gm_timer = setInterval(this.check_for_gm.bind(this), 2000);

        // Make the placeholder change when the input_box gains focus.
        input_box.addEventListener('focus', this.on_input_box_focus.bind(this), true);
        input_box.addEventListener('blur', this.on_input_box_unfocus.bind(this), true);
        $(input_box).keydown(this.on_input_box_keypress.bind(this));

        //=================================================
        // Prevent chat de-focus.
        //=================================================
        var g_MouseEvent = false;
        $("input").blur(function () {
            if (g_MouseEvent) {
                $(this).focus();
                g_MouseEvent = false;
            }
        });

        $("body").mousedown(function () {
            g_MouseEvent = false;
        });

        $("#chat").mousedown(function (evt) {
            g_MouseEvent = true;
            evt.stopPropagation();
        });

        // Preference: Chat.Enabled
        if (app.sio_get("Chat", "Enabled") != 0) {
            var anchor = app.sio_get("Chat", "Anchor");
            var pos_x = app.sio_get("Chat", "PositionX");
            var pos_y = app.sio_get("Chat", "PositionY");
            var width = app.sio_get("Chat", "Width");
            var height = app.sio_get("Chat", "Height");

            var anchor_y = anchor.indexOf('t') !== -1 ? "top" : "bottom";
            var anchor_x = anchor.indexOf('r') !== -1 ? "right" : "left";

            var el = $("#chat");
            el.css(anchor_x, pos_x);
            el.css(anchor_y, pos_y);
            el.css("width", width);
            el.css("height", height);

            $("#chat").show();
        }

        // Preference: Scaling
        $("body").css("zoom", app.sio_get("WebKit", "SampleScale") * 0.85);

        // Error catching
        window.onerror = (function (msg, url, line, col, error) {
            this.addSystemMessage(msg, "255,0,0");
        }).bind(this);
    };

};